sudo: require
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake-3.6
compiler:
  - gcc
  - clang
install:
script: cmake . && make && ./PiXiuPlus