language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise
    packages:
      - clang-3.7
compiler: clang
install: export CXX="clang++-3.7" CC="clang-3.7"
script: cmake . && make && ./PiXiuPlus