sudo: required
language: generic

before_install:
  -mkdir build-debug
  -cd build-debug/
install:
  sudo apt-get install cmake &&
  cmake .. &&
  make &&
  ./PiXiuPlus

before_script:
srcipt:
after_success:
after_failure:
after_script: